// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: productfinder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductFinderClient is the client API for ProductFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductFinderClient interface {
	// Get a product by its id
	GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
	// Return all available products
	ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error)
	// Return the price of a given product
	GetPriceOfProduct(ctx context.Context, in *GetPriceOfProductReq, opts ...grpc.CallOption) (*GetPriceOfProductResp, error)
	// Return the price of multiple given products
	BatchGetPriceOfProduct(ctx context.Context, in *BatchGetPriceOfProductReq, opts ...grpc.CallOption) (*BatchGetPriceOfProductResp, error)
}

type productFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewProductFinderClient(cc grpc.ClientConnInterface) ProductFinderClient {
	return &productFinderClient{cc}
}

func (c *productFinderClient) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	out := new(GetProductResp)
	err := c.cc.Invoke(ctx, "/proto.ProductFinder/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFinderClient) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error) {
	out := new(ListProductsResp)
	err := c.cc.Invoke(ctx, "/proto.ProductFinder/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFinderClient) GetPriceOfProduct(ctx context.Context, in *GetPriceOfProductReq, opts ...grpc.CallOption) (*GetPriceOfProductResp, error) {
	out := new(GetPriceOfProductResp)
	err := c.cc.Invoke(ctx, "/proto.ProductFinder/GetPriceOfProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productFinderClient) BatchGetPriceOfProduct(ctx context.Context, in *BatchGetPriceOfProductReq, opts ...grpc.CallOption) (*BatchGetPriceOfProductResp, error) {
	out := new(BatchGetPriceOfProductResp)
	err := c.cc.Invoke(ctx, "/proto.ProductFinder/BatchGetPriceOfProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductFinderServer is the server API for ProductFinder service.
// All implementations must embed UnimplementedProductFinderServer
// for forward compatibility
type ProductFinderServer interface {
	// Get a product by its id
	GetProduct(context.Context, *GetProductReq) (*GetProductResp, error)
	// Return all available products
	ListProducts(context.Context, *ListProductsReq) (*ListProductsResp, error)
	// Return the price of a given product
	GetPriceOfProduct(context.Context, *GetPriceOfProductReq) (*GetPriceOfProductResp, error)
	// Return the price of multiple given products
	BatchGetPriceOfProduct(context.Context, *BatchGetPriceOfProductReq) (*BatchGetPriceOfProductResp, error)
	mustEmbedUnimplementedProductFinderServer()
}

// UnimplementedProductFinderServer must be embedded to have forward compatible implementations.
type UnimplementedProductFinderServer struct {
}

func (UnimplementedProductFinderServer) GetProduct(context.Context, *GetProductReq) (*GetProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductFinderServer) ListProducts(context.Context, *ListProductsReq) (*ListProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductFinderServer) GetPriceOfProduct(context.Context, *GetPriceOfProductReq) (*GetPriceOfProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceOfProduct not implemented")
}
func (UnimplementedProductFinderServer) BatchGetPriceOfProduct(context.Context, *BatchGetPriceOfProductReq) (*BatchGetPriceOfProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetPriceOfProduct not implemented")
}
func (UnimplementedProductFinderServer) mustEmbedUnimplementedProductFinderServer() {}

// UnsafeProductFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductFinderServer will
// result in compilation errors.
type UnsafeProductFinderServer interface {
	mustEmbedUnimplementedProductFinderServer()
}

func RegisterProductFinderServer(s grpc.ServiceRegistrar, srv ProductFinderServer) {
	s.RegisterService(&ProductFinder_ServiceDesc, srv)
}

func _ProductFinder_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFinderServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductFinder/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFinderServer).GetProduct(ctx, req.(*GetProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFinder_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFinderServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductFinder/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFinderServer).ListProducts(ctx, req.(*ListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFinder_GetPriceOfProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceOfProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFinderServer).GetPriceOfProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductFinder/GetPriceOfProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFinderServer).GetPriceOfProduct(ctx, req.(*GetPriceOfProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductFinder_BatchGetPriceOfProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetPriceOfProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductFinderServer).BatchGetPriceOfProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductFinder/BatchGetPriceOfProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductFinderServer).BatchGetPriceOfProduct(ctx, req.(*BatchGetPriceOfProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductFinder_ServiceDesc is the grpc.ServiceDesc for ProductFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductFinder",
	HandlerType: (*ProductFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductFinder_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductFinder_ListProducts_Handler,
		},
		{
			MethodName: "GetPriceOfProduct",
			Handler:    _ProductFinder_GetPriceOfProduct_Handler,
		},
		{
			MethodName: "BatchGetPriceOfProduct",
			Handler:    _ProductFinder_BatchGetPriceOfProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "productfinder.proto",
}
