name: Deploy to GitHub Pages

on:
  push:
    branches: 'website'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          node-version-file: website/package.json
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: |
          cd website
          npm install

      - name: build
        env:
          BASE_PATH: '/wireman-svelte'
        run: |
          cd website
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
